### ISSUE TITLE
Console input not validated

### ISSUE THREAD

**Issue by Drru97** [bohdanD/Dejkstra#1]
Users are able to input float point values and strings from console, while expected input is integer number. This issue causes FormatException in the runtime. 
Also, count of tops value is not checked to be greater than 0. This causes OverflowException while user inputs negative number.
https://github.com/bohdanD/Dejkstra/blob/d5e95614b61423f65c2a6283a90097ab83045c5b/Program.cs#L21
https://github.com/bohdanD/Dejkstra/blob/d5e95614b61423f65c2a6283a90097ab83045c5b/Program.cs#L36
https://github.com/bohdanD/Dejkstra/blob/d5e95614b61423f65c2a6283a90097ab83045c5b/Program.cs#L41
https://github.com/bohdanD/Dejkstra/blob/d5e95614b61423f65c2a6283a90097ab83045c5b/Program.cs#L42

**Comment by bohdanD** [comment]
Input validation not supported by design. Thanks anyway.
