### ISSUE TITLE
Invalid way length calculation

### ISSUE THREAD

**Issue by Drru97** [bohdanD/Dejkstra#2]
I've tried to calculate way length on simple graph.

![dejkstra](https://user-images.githubusercontent.com/11758916/33616683-40e65dae-d9e6-11e7-83e4-390237598b90.jpg)

As expected, shortest way is calculated correctly (in this example 0 -> 1 -> 2 -> 3). From other side, way length is not calculated correctly. As you can see, way length should be 3 + 1 + 2 = 6, but program prints 2. 

![untitled](https://user-images.githubusercontent.com/11758916/33616733-70445920-d9e6-11e7-952a-767af5ac7e16.png)

**Comment by bohdanD** [comment]
Length calculating resolved. Thank you for your contribution.
